### PR TITLE
Restore --help flag functionality

### PR DESCRIPTION
**Pull request by rendinam**
Additional fix to add to #20.

### CODE REVIEW

**Comment by pllim** [comment]
Good catch! Any chance you can squash the commits?

**Comment by pllim** [comment]
Oh noes! I just realized you modified your `master` branch. That is not recommended. You should save your change file somewhere outside git, do a hard reset on your `master` so it is in sync with upstream master, create a new feature branch, reapply your changes to the feature branch, open a PR from the feature branch.

**Comment by rendinam** [comment]
I'll do just that. Thanks for the suggestions. Part of the objective here was to get familiar and shake out the problems with a small edit, so it's no trouble.

**Comment by pllim** [comment]
Yes, I figured you can use this as training. That's why I didn't just commit that one-liner myself in `master`. :wink:

**Pull request closed without merging**
